[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true