name: 部署又拍云
on: 
  repository_dispatch:
    types: [depoly_upyun]
  workflow_dispatch: 
jobs:
  Deploy-UPYUN:
    runs-on: ubuntu-latest
    steps:
      - name: 检出源码
        uses: actions/checkout@v3 
      - name: 设置 Node.js
        uses: actions/setup-node@v3 
        with:
          node-version: '18.16.0' 
      - name: 编译静态页面
        run: |
          npm install -g hexo-cli
          npm install
          hexo clean
          hexo generate -config yml/my.covear.top.yml 
      - name: 部署到又拍云
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_url }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          protocol: ftp
          local-dir: ./public/
          dangerous-clean-slate: true
      - name: 触发评论 API
        run: |
          curl "https://api.hnest.eu.org/doit?token=Z2hwX05VejBmZzBFSjFuVXBmSUtLU1lDZjJpN3RpdVlnZzB5VjdtRA==&hook_name=deployment_status&repopath=DavidDengHui&reponame=HNest&username=DavidDengHui&state=success&url=https://my.covear.top"
          